# Generated by Django 4.2.1 on 2023-05-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_freelancer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
