# Generated by Django 4.2.1 on 2023-05-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUsers', '0002_alter_customuser_user_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_bio',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
