# Generated by Django 4.2.1 on 2023-05-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUsers', '0003_alter_customuser_user_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_profile_picture',
            field=models.ImageField(blank=True, default=None, upload_to='image/%y'),
        ),
    ]
