# Generated by Django 4.2.1 on 2023-05-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUsers', '0004_alter_customuser_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_profile_picture',
            new_name='profile_picture',
        ),
    ]
